server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?createDatabaseIfNotExist=true
    username: root
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
